name: example
run-name: ${{ github.actor }} is learning GitHub Actions
on:
- push
jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      DEPLOYMENT: 'prod'
      PYTHON_VERSION_TEST: '3.10'
      PYTHON_VERSION_PROD: '3.8'
    steps:
      - name: Check out repo code first
        uses: actions/checkout@v3
        id: checkout
      - name: Setup Python for ${{ env.DEPLOYMENT }}
        if: env.DEPLOYMENT == 'test'
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION_TEST }}
        id: setup-python-test
      - name: Setup Python for ${{ env.DEPLOYMENT }}
        if: env.DEPLOYMENT == 'prod'
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION_PROD }}
        id: setup-python-prod
      - name: Check Python version
        run: python --version
        id: python-version
      - name: Run and test application code
        run: python example.py
        id: run-example

